//---------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace AssemblyCSharp
{
	/**
	 * A base interaction state for all interactions such as gui displays
	 * @author Jakob Wilson
	 * */
	public abstract class InteractionState
	{
		public GameObject actee; 	/**The completing the action*/
		public GameObject actor;	/**The gameobject triggering the interaction*/

		/**
		 * The constructor is called with one required param: the actee which is the object being acted upon
		 * It also has oe optional param called actor which is the object acting upon the state machine
		 * Actor can also be changed on the fly to allow for more dynamic behaviour
		 * */
		public InteractionState (GameObject _actee, GameObject _actor = null)
		{
			this.actee = _actee;
			this.actor = _actor;	
		}

		/**
		 * The generic bahaviour of the InteractionState
		 * 
		 * */
		public abstract InteractionState Behave();

		public virtual void Suspend()
		{
			//do nothing
		}
	}
}

