//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEditor;
using UnityEngine.UI;

namespace AssemblyCSharp
{
	public class InteractMC_State:InteractionState
	{
		
		private GameObject _cvsQuestion;
		private accessMCCvs _cvsQuestMC;

		private bool _ansEntered;
		
		/**
		 * Sets default values and calls base constructor
		 * */
		public InteractMC_State (GameObject _actee, GameObject _actor = null):base(_actee, _actor)
		{
			this._ansEntered = false;
		}
		
		/**
		 * Displays a GUI with an interact button, 
		 * if the button is clicked, then the state is transitioned to an Opening State(See OpeningState.cs)
		 * 
		 * */
		public override InteractionState Behave ()
		{
			//if the gui doesn't exist, create it
			if (_cvsQuestion == null && this.actor != null) 
			{
				if(this.actor.tag == "Player")
				{
					this._cvsQuestion = GameObject.Instantiate(Resources.Load ("QCanvas/TFCvs") as GameObject);

					//this.cvsQuest = this._cvsQuestion.GetComponentInChildren<accessTFCvs> ();

					string quest = "Is Unity is AMAZING?";
					//string[] ans = {"Everything","Something","Nothing","Particle Physics"};

					//this.cvsQuest.setQuestion (quest);
					//this.cvsQuest.setAnswers (ans);
				}
			}
			
			//if the button has been clicked,
			if (this._ansEntered) {
				//Debug.Log("Answer Typed "  + this.cvsQuest.toggleTF.ToString());
				//this.cvsQuest.cleanListeners();
				GameObject.Destroy(this._cvsQuestion);	//clean up the question 
				return new OpeningState (this.actee, this.actor);	//open the door
			}
			else
				return this;//continue incurrent state
			
		}
		
		/**
		 * 
		 * */
		public override void Suspend(Collider c = null)
		{
			Debug.Log("Cleared event");
			GameObject.Destroy (this._cvsQuestion);
		}

	}
}

