//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace States
{
	public class LockedState:InteractionState
	{
		public LockedState(GameObject _actee, GameObject _actor):base(_actee, _actor)
		{
			//nothing
		}
		public override InteractionState Behave ()
		{
			return this;
		}
	}
}
