//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


/**
 * Filename: OpeningState
 * Author: Jakob Wilson
 * Created: 5/22/2015
 * Revision: 1
 * Rev. Date: 
 * Rev. Author: 
 * */
using System;
using UnityEngine;
namespace States
{
	/**
	 * A momentary state that simply plays the door opening animation, 
	 * changes the emission color of the main material to green, 
	 * then returns an idle state so no more actions can be done to the door.
	 * */
	public class OpeningState:InteractionState
	{
		private Animator anim;/**The animator so we cna playback animations*/
		private Renderer rend;/**The renderer so we can change the color of the frame lights*/

		public OpeningState (GameObject _actee, GameObject _actor):base(_actee, _actor){}

		public override InteractionState Behave ()
		{
				this.anim = this.actee.GetComponent<Animator> ();
				this.rend = this.actee.GetComponentInChildren<Renderer>();
				
				// if we have an animator, play the animation
				if(this.anim != null)
					this.anim.Play("OpenDoors");
				
				//if we have the renderer, change the frame light color
				if(this.rend != null)
				{
					rend.material.EnableKeyword ("_EMISSION");
					rend.material.SetColor("_EmissionColor", Color.green);
				}
				
				return new OpenState(this.actee, this.actor);
		}
	}
}

