//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Threading;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.UI;

namespace KOSTests
{
	/**
	 * Tests all the GUI interfaces to ensure that the correct elements can be accessed
	 * */
	[TestFixture]
	[Category("Project KOS Tests")]
	internal class DatabaseTests
	{
		[Test]
		public void ConnectToDatabase()
		{
			Assert.Pass ();
		}
		

	}
}

